= Deploying a MySQL ansible role

In this exercise, you will create a role to deploy MySQL.

**NOTE**: All the tasks in this role needs to be executed as root. You can surround all the task in a block, and add become: true

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
tasks:

- block:

  - name: Install httpd packages
    yum:

  become: true
----

[#init]
== Create ansible role skeleton

**1) Create an empty ansible role**

Run *ansible-galaxy role init* to create an empty role skeleton:

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
$ ansible-galaxy role init mysql
----

[#vars]
== Create group vars

**2) Create some MySQL group vars we'll need to use:**

Create a folder named group_vars in your working folder, and inside group_vars, create another folder named all.
Inside this folder, create a file named database.yml with the following variables:

- mysql_user: usal
- mysql_password: usal2022
- mysql_database: employees
- mysql_table: employee

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
group_vars/all/database.yml
---
mysql_user: usal
mysql_password: usal2022
mysql_database: employees
mysql_table: employee
----


[#yum]
== Install mysql server

**3) Add a task to install mysqld package using the yum module**

Install the packages:

    - mysql-server
    - python3-PyMySQL

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Install mysql-server and python3-PyMySQL packages
    yum:
      name: # Complete
      state: # Complete
----

[#service]
== Start and enable mysqld service

**4) Add a task to start and enable mysqld service using the service module**

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Enable and start mysql service
    service:
      name: # Complete
      enabled: # Complete
      state: # Complete
----


[#firewall]
== Open MySQL service in Firewall 

**5) Add a task to Open MySQL service in Firewall **

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Open MySQL service in Firewall 
    firewalld:
      permanent: # Complete
      state: # Complete
      service: # Complete
      immediate: # Complete
----


[#mysqluser]
== Add the user to mysql

**6) Add a task to add the user to MySQL **

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Add user to MySQL
    mysql_user:
      name: # Complete
      password: # Complete
      host: "%"
      priv: '*.*:ALL'
      state: # Complete
    no_log: true
----

[#mysqldb]
== Add the database to mysql

**7) Add a task to add the database to MySQL **

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: create a new database  
    mysql_db:
      name: # Complete
      state: present
----

