= Deploying a HTTPD ansible role

In this exercise, you will create a role to deploy and configure HTTPD.

**NOTE**: All the tasks in this role needs to be executed as root. You can surround all the task in a block, and add become: true

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
tasks:

- block:

  - name: Install httpd packages
    yum:

  become: true
----

[#init]
== Create ansible role skeleton

**1) Create an empty ansible role**

Run *ansible-galaxy role init* to create an empty role skeleton:

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
$ ansible-galaxy role init httpd
----

[#yum]
== Install httpd

**2) Add a task to Install the following packages using the yum module**

    - httpd
    - php
    - php-mysqlnd

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Install httpd packages
    yum:
      name: # Complete 
      state: # Complete 
----

[#firewall]
== Open httpd service in Firewall 

**3) Add a task to Open http service in Firewall **

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Open HTTPD service in Firewall 
    firewalld:
      permanent: # Complete
      state: # Complete
      service: # Complete
      immediate: # Complete
----

[#selinux]
== Allow httpd connections to MySQL database

**4) Add a task to allow httpd connections to MySQL database enabling SELinux boolean httpd_can_network_connect_db**

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Allow httpd connections to a database with SELinux
    seboolean:
      name: httpd_can_network_connect_db
      persistent: # Complete 
      state: # Complete 
----

[#service]
== Start and enable httpd service

**5) Add a task to start and enable httpd service using the service module**

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Enable and start httpd service
    service:
      name: # Complete
      enabled: # Complete
      state: # Complete
----

