= Deploying a HAProxy ansible role

In this exercise, you will create a role to deploy and configure HAProxy.

**NOTE**: All the tasks in this role needs to be executed as root. You can surround all the task in a block, and add become: true

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
tasks:

- block:

  - name: Install httpd packages
    yum:

  become: true
----

[#init]
== Create ansible role skeleton

**1) Create an empty ansible role**

Run *ansible-galaxy role init* to create an empty role skeleton:

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
$ ansible-galaxy role init haproxy
----

[#yum]
== Install HAProxy

**2) Add a task to install the following packages using the yum module**

- haproxy
- socat

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Install haproxy packages
    yum:
      name: # Complete
      state: # Complete
----

[#template]
== Create HAProxy template

**3) Create the file haproxy.cfg.j2 in templates folder.**

The template file should be like:

[.lines_7]
[source,conf,subs="+macros,+attributes"]
----
global
  daemon
  group  haproxy
  log  /dev/log local0
  maxconn  10000
  pidfile  /var/run/haproxy.pid
  user  haproxy

defaults
  log  global
  mode  http
  retries  3
  timeout  http-request 10s
  timeout  queue 1m
  timeout  connect 10s
  timeout  client 1m
  timeout  server 1m
  timeout  check 10s

frontend main
    mode http
    default_backend usal
    
    # Complete
    # bind *:80

backend usal
    balance roundrobin
    
    # Complete
    # server example1 10.0.0.1:80
    # server example2 10.0.0.2:80
----

[#copytemplate]
== Copy HAProxy template

**4) Add a task to copy HAProxy template.**

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Configure haproxy
    template:
      src: # Complete
      dest: /etc/haproxy/haproxy.cfg
      owner: root
      group: root
      mode: 0644
----

[#firewall]
== Open haproxy service in Firewall 

**5) Add a task to Open HAProxy (http) service in Firewall **

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Open HAProxy service in Firewall 
    firewalld:
      permanent: # Complete
      state: # Complete
      service: # Complete
      immediate: # Complete
----

[#service]
== Enable and start HAProxy

**6) Add a task to enable and start HAProxy**

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
  - name: Enable and start haproxy
    service:
      name: # Complete
      enabled: # Complete
      state: # Complete
----

