= Create an ansible playbook to deploy the Web solution

Create a playbook to deploy MySQL, Web Server and HAProxy roles using the Web collection.

[#include]
== Create an ansible playbook to deploy mysql, httpd and haproxy

**1) Create three include_role tasks to include mysql, httpd and haproxy roles**

Add the condition to deploy mysql only in **mysql** group, httpd only in **webserver** group and haproxy in **haproxy** group

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
web.yml
---
- name: Deploy Web solution
  hosts: all

  tasks:

    - name: Deploy MySQL
      include_role:
        name: mysql
      when: # Complete - this role should run only in mysql host group

    - name: Deploy HTTPD server
      include_role:
        name: httpd
      when: # Complete - this role should run only in webserver hosts group

    - name: Deploy HAProxy
      include_role:
        name: haproxy
      when: # Complete - this role should run only in haproxy host group
----

[#webcontent]
== Copy the content to the web servers

**2) Add a task to copy the content to the web servers**

Copy the template files , and add a task to copy the content from the template files to the web servers.

Add a variable named mysql with the value "CREATE TABLE IF NOT EXISTS employee ( emp_id INT AUTO_INCREMENT PRIMARY KEY, emp_name VARCHAR(255) NOT NULL, emp_address VARCHAR(255) NOT NULL, emp_salary INT, emp_join DATE )"

[.lines_7]
[source,yaml,subs="+macros,+attributes"]
----
        - name: Add web content
          vars:
            mysql_table_sql: "CREATE TABLE IF NOT EXISTS employee ( emp_id INT AUTO_INCREMENT PRIMARY KEY, emp_name VARCHAR(255) NOT NULL, emp_address VARCHAR(255) NOT NULL, emp_salary INT, emp_join DATE )"
          template:
            src: # Complete 
            dest: # Complete 
          become: true
          loop:
            - index.php
            - add_employee.php
          when: # Complete - this task should run only in webserver hosts group
----

[#test]
== Deploy the solution

**4) Run the playbook web.yml passing as argument the inventory created**

[.lines_7]
[source,bash,subs="+macros,+attributes"]
----
ansible-playbook -i inventory web.yml
----
