= Creating Ansible Roles

[.text-center.strong]
== Introduction

Roles let you automatically load related vars, files, tasks, handlers, and other Ansible artifacts based on a known file structure. After you group your content in roles, you can easily reuse them and share them with other users.

[.tiles.browse]
== Exercises

=== 1. Create an Ansible Role to deploy a MySQL database

Create an asnible role to deploy MYSQL server and create a database.

xref:02-role-mysql.adoc[Start]

=== 2. Create an Ansible Role to deploy a Web Server

Create an asnible role to deploy two web servers, which returns some content stored in the databsase.

xref:03-role-httpd.adoc[Start]

=== 3. Create an Ansible Role to deploy a HAProxy Load Balancer

Create an asnible role to deploy an HAProxy to load balance the requests to the web server.

xref:04-role-haproxy.adoc[Start]

=== 4. Create a playbook to deploy the whole solution

Create a playbook to use the MySQL, Web Server and HAProxy roles.

xref:05-role-solution.adoc[Start]